name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.0]
        laravel: [^8.0, ^6.0]
        include:
          - laravel: ^8.0
            testbench: ^6.0
          - laravel: ^6.0
            testbench: ^4.0
        exclude:
          - laravel: ^6.0
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require "illuminate/config:${{ matrix.laravel }}" "illuminate/routing:${{ matrix.laravel }}" "illuminate/support:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:^${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        env:
          VIVA_API_KEY: ${{ secrets.VIVA_API_KEY }}
          VIVA_CLIENT_ID: ${{ secrets.VIVA_CLIENT_ID }}
          VIVA_CLIENT_SECRET: ${{ secrets.VIVA_CLIENT_SECRET }}
          VIVA_ENVIRONMENT: demo
          VIVA_MERCHANT_ID: ${{ secrets.VIVA_MERCHANT_ID }}
          VIVA_PUBLIC_KEY: ${{ secrets.VIVA_PUBLIC_KEY }}
          VIVA_SOURCE_CODE: ${{ secrets.VIVA_SOURCE_CODE }}
        run: vendor/bin/phpunit --verbose --whitelist=src --coverage-clover=build/coverage/coverage.clover

      - name: Upload coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover build/coverage/coverage.clover
